### ISSUE TITLE
No .xcodeproj file in zip

### ISSUE THREAD

**Issue by michelledaksha** [akoziaruk/SingleView#1]
Hi, there.  This is Michelle.  I'm not sure if you'll see this today or not, and if not no worries, but I was attempting to view your submission and there is no .xcodeproj file included in the zip download.  If you do see this and have time, please update your repo with the .xcodeproj file so I can view it.  Thanks!

**Comment by akoziaruk** [comment]
Hi Michelle. Thanks for noticing, added .xcodeproj.
